use serde::{Deserialize, Serialize};

use crate::model::edge::Confidence;

/// An N-ary relationship involving three or more nodes.
///
/// HyperEdges capture group relationships that cannot be expressed as a
/// single binary edge — e.g. "ClassA, ClassB, ClassC all implement InterfaceX",
/// or "functions foo, bar, baz participate in the authentication flow".
///
/// The semantic extractor generates at most 3 hyperedges per file.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct HyperEdge {
    #[serde(default)]
    /// Stable normalized identifier (generated by [`crate::model::make_id`]).
    pub id: String,

    /// Human-readable description of the group relationship.
    pub label: String,

    /// IDs of all nodes participating in this relationship (at least 3).
    pub nodes: Vec<String>,

    /// Relation type. Common values: `"participate_in"`, `"implement"`, `"form"`.
    pub relation: String,

    /// Confidence level for this group relationship.
    pub confidence: Confidence,

    /// Numeric confidence in [0.0, 1.0].
    pub confidence_score: f64,

    /// Relative path of the source file this was extracted from.
    pub source_file: String,
}

impl HyperEdge {
    pub fn new(
        id: impl Into<String>,
        label: impl Into<String>,
        nodes: Vec<String>,
        relation: impl Into<String>,
        confidence: Confidence,
        source_file: impl Into<String>,
    ) -> Self {
        let score = confidence.default_score();
        Self {
            id: id.into(),
            label: label.into(),
            nodes,
            relation: relation.into(),
            confidence_score: score,
            confidence,
            source_file: source_file.into(),
        }
    }
}

impl Eq for HyperEdge {}
