use serde::{Deserialize, Serialize};

use crate::model::id::{normalize_id, normalize_label};

/// Classifies what kind of content a node was extracted from.
/// Serializes as lowercase (e.g. `"code"`, `"document"`) to match Python output.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FileType {
    Code,
    Document,
    Paper,
    Image,
    /// A rationale node: captures the *why* behind a decision, extracted
    /// from docstrings or design comments.
    Rationale,
}

impl std::fmt::Display for FileType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let s = match self {
            FileType::Code => "code",
            FileType::Document => "document",
            FileType::Paper => "paper",
            FileType::Image => "image",
            FileType::Rationale => "rationale",
        };
        write!(f, "{s}")
    }
}

/// A single entity in the knowledge graph.
///
/// Nodes are produced by both the AST extractor (deterministic, free) and
/// the semantic extractor (LLM-powered). When merging, last-write-wins on
/// duplicate IDs — semantic results override AST ones.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Node {
    /// Stable, normalized identifier. Generated by [`crate::model::make_id`].
    /// Format: `"stem_entityname"` (lowercase, underscores only).
    pub id: String,

    /// Human-readable display name (e.g. `"MyClass"`, `"process_batch"`).
    pub label: String,

    /// What kind of source file this entity came from.
    pub file_type: FileType,

    /// Relative path of the source file within the analyzed corpus.
    pub source_file: String,

    /// Source location hint, e.g. `"L42"`. Empty string if unknown.
    #[serde(default)]
    pub source_location: String,

    /// Community assignment from the Louvain clustering step.
    /// `None` until the cluster phase assigns it.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub community: Option<usize>,

    /// Optional qualified/namespaced label used for disambiguation when many
    /// symbols share the same short name (e.g. `MyNamespace.MyClass.Dispose`
    /// vs `OtherNamespace.OtherClass.Dispose`). Populated by extractors that
    /// track enclosing scope; left `None` when the raw `label` is already
    /// unambiguous or when the extractor does not yet emit scopes.
    ///
    /// Consumers should prefer `qualified_label` when present and fall back
    /// to `label` otherwise.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub qualified_label: Option<String>,

    /// Which extractor produced this node: "tree-sitter", "tree-sitter-stack-graphs",
    /// "llm-anthropic", etc.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub extractor: Option<String>,

    /// Resolution status: "resolved", "unresolved", "ambiguous", "heuristic", "inferred".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub resolution_status: Option<String>,

    /// Optional plan_id for virtual/planned entities. When set, this node
    /// represents an intended change in a planning workspace rather than
    /// extracted source code. Filtered out of standard queries by default.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub plan_id: Option<String>,
}

impl Node {
    pub fn new(
        id: impl Into<String>,
        label: impl Into<String>,
        file_type: FileType,
        source_file: impl Into<String>,
    ) -> Self {
        let id = id.into();
        let label = label.into();
        Self {
            id: normalize_id(&id),
            label: normalize_label(&label),
            file_type,
            source_file: source_file.into(),
            source_location: String::new(),
            community: None,
            qualified_label: None,
            extractor: None,
            resolution_status: None,
                    plan_id: None,
        
    }

    pub fn with_source_location(mut self, source_location: impl Into<String>) -> Self {
        self.source_location = normalize_source_location(&source_location.into());
        self
    }

    /// Attach a qualified (scope-prefixed) label to this node. Trimmed;
    /// an empty string becomes `None`.
    pub fn with_qualified_label(mut self, qualified: impl Into<String>) -> Self {
        let s = qualified.into();
        let trimmed = s.trim();
        self.qualified_label = if trimmed.is_empty() {
            None
        } else {
            Some(trimmed.to_string())
        };
        self
    }

    /// The label to display to users. Prefers `qualified_label` when
    /// populated, falls back to the plain `label`.
    pub fn display_label(&self) -> &str {
        self.qualified_label.as_deref().unwrap_or(&self.label)
    }
}

pub fn normalize_source_location(location: &str) -> String {
    location.trim().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn file_type_serializes_lowercase() {
        assert_eq!(serde_json::to_string(&FileType::Code).unwrap(), r#""code""#);
        assert_eq!(
            serde_json::to_string(&FileType::Document).unwrap(),
            r#""document""#
        );
        assert_eq!(
            serde_json::to_string(&FileType::Rationale).unwrap(),
            r#""rationale""#
        );
    }

    #[test]
    fn node_roundtrip() {
        let node = Node::new("mymod_myclass", "MyClass", FileType::Code, "src/mymod.py");
        let json = serde_json::to_string(&node).unwrap();
        let back: Node = serde_json::from_str(&json).unwrap();
        assert_eq!(back.id, "mymod_myclass");
        assert_eq!(back.label, "MyClass");
        assert_eq!(back.file_type, FileType::Code);
        assert!(back.community.is_none());
    }

    #[test]
    fn node_normalizes_id_and_label() {
        let node = Node::new(" Foo::Bar ", " `Foo::Bar` ", FileType::Code, "src/x.rs");
        assert_eq!(node.id, "foo_bar");
        assert_eq!(node.label, "Foo::Bar");
    }

    #[test]
    fn node_can_store_source_location() {
        let node = Node::new("foo", "Foo", FileType::Code, "src/foo.rs")
            .with_source_location(" L12:C5-L18:C2 ");
        assert_eq!(node.source_location, "L12:C5-L18:C2");
    }
}
