/// Markdown `GRAPH_REPORT.md` generation.
///
/// Sections (in order):
///   1. Corpus Warnings
///   2. Summary table
///   3. God Nodes
///   4. Surprising Connections
///   5. Hyperedges
///   6. Communities (cohesion + members)
///   7. Ambiguous Edges
///   8. Knowledge Gaps (isolated nodes)
///   9. Suggested Questions
use std::fmt::Write as FmtWrite;
use std::fs;
use std::path::{Path, PathBuf};

use crate::analyze::AnalysisResult;
use crate::cluster::CommunityStats;
use crate::detect::CorpusWarning;
use crate::model::graph::GrapheniumGraph;
use crate::model::Confidence;

// ── Public types ───────────────────────────────────────────────────────────────

/// All data required to render a report.
pub struct ReportInput<'a> {
    pub graph: &'a GrapheniumGraph,
    pub community_stats: &'a [CommunityStats],
    pub analysis: &'a AnalysisResult,
    pub corpus_warnings: &'a [CorpusWarning],
    /// Total LLM input tokens consumed during extraction (0 if no semantic pass).
    pub input_tokens: u64,
    /// Total LLM output tokens produced during extraction.
    pub output_tokens: u64,
    /// Human-readable corpus / project title.
    pub title: String,
}

// ── Public API ─────────────────────────────────────────────────────────────────

/// Render the report to a Markdown string.
pub fn render_report(r: &ReportInput<'_>) -> String {
    let mut s = String::with_capacity(8192);

    write_header(&mut s, r);
    write_corpus_warnings(&mut s, r.corpus_warnings);
    write_summary(&mut s, r);
    write_god_nodes(&mut s, r);
    write_surprising(&mut s, r);
    write_hyperedges(&mut s, r.graph);
    write_communities(&mut s, r.community_stats);
    write_ambiguous_edges(&mut s, r.graph);
    write_knowledge_gaps(&mut s, r.graph);
    write_questions(&mut s, r);

    s
}

/// Write `GRAPH_REPORT.md` to `out_dir` and return the file path.
pub fn write_report(r: &ReportInput<'_>, out_dir: &Path) -> crate::Result<PathBuf> {
    fs::create_dir_all(out_dir)?;
    let content = render_report(r);
    let path = out_dir.join("GRAPH_REPORT.md");
    fs::write(&path, content)?;
    Ok(path)
}

// ── Section renderers ─────────────────────────────────────────────────────────

fn write_header(s: &mut String, r: &ReportInput<'_>) {
    let _ = writeln!(s, "# Knowledge Graph Report: {}", r.title);
    let _ = writeln!(s);
    let _ = writeln!(s, "> Generated by **Graphenium**");
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_corpus_warnings(s: &mut String, warnings: &[CorpusWarning]) {
    let _ = writeln!(s, "## Corpus Warnings");
    let _ = writeln!(s);
    if warnings.is_empty() {
        let _ = writeln!(s, "_No warnings._");
    } else {
        for w in warnings {
            let _ = writeln!(s, "- ⚠️  {w}");
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_summary(s: &mut String, r: &ReportInput<'_>) {
    let g = r.graph;
    let total_edges = g.edge_count();
    let (mut ext, mut inf, mut amb) = (0usize, 0usize, 0usize);
    for e in g.edges_iter() {
        match e.confidence {
            Confidence::Extracted => ext += 1,
            Confidence::Inferred => inf += 1,
            Confidence::Ambiguous => amb += 1,
        }
    }
    let pct = |n: usize| {
        if total_edges == 0 {
            "0%".to_string()
        } else {
            format!("{:.0}%", 100.0 * n as f64 / total_edges as f64)
        }
    };

    let _ = writeln!(s, "## Summary");
    let _ = writeln!(s);
    let _ = writeln!(s, "| Metric | Value |");
    let _ = writeln!(s, "|--------|-------|");
    let _ = writeln!(s, "| Nodes | {} |", g.node_count());
    let _ = writeln!(s, "| Edges | {} |", total_edges);
    let _ = writeln!(s, "| Communities | {} |", r.community_stats.len());
    let _ = writeln!(s, "| Hyperedges | {} |", g.hyperedges.len());
    let _ = writeln!(s, "| EXTRACTED edges | {} ({}) |", ext, pct(ext));
    let _ = writeln!(s, "| INFERRED edges | {} ({}) |", inf, pct(inf));
    let _ = writeln!(s, "| AMBIGUOUS edges | {} ({}) |", amb, pct(amb));
    let _ = writeln!(s, "| Input tokens | {} |", r.input_tokens);
    let _ = writeln!(s, "| Output tokens | {} |", r.output_tokens);
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_god_nodes(s: &mut String, r: &ReportInput<'_>) {
    let _ = writeln!(s, "## God Nodes");
    let _ = writeln!(s);
    if r.analysis.god_nodes.is_empty() {
        let _ = writeln!(s, "_None detected._");
    } else {
        let _ = writeln!(s, "| Label | Degree | Community | File |");
        let _ = writeln!(s, "|-------|--------|-----------|------|");
        for n in r.analysis.god_nodes.iter().take(10) {
            let comm = n.community.map_or("—".to_string(), |c| c.to_string());
            let _ = writeln!(
                s,
                "| `{}` | {} | {} | `{}` |",
                n.display_label(),
                n.degree,
                comm,
                n.source_file
            );
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_surprising(s: &mut String, r: &ReportInput<'_>) {
    let _ = writeln!(s, "## Surprising Connections");
    let _ = writeln!(s);
    if r.analysis.surprising.is_empty() {
        let _ = writeln!(s, "_None detected._");
    } else {
        let _ = writeln!(s, "| Source | Target | Relation | Score | Reasons |");
        let _ = writeln!(s, "|--------|--------|----------|-------|---------|");
        for e in r.analysis.surprising.iter().take(10) {
            let src_label = r
                .graph
                .node_data(&e.source)
                .map_or(e.source.as_str(), |n| n.display_label());
            let tgt_label = r
                .graph
                .node_data(&e.target)
                .map_or(e.target.as_str(), |n| n.display_label());
            let _ = writeln!(
                s,
                "| `{}` | `{}` | {} | {:.1} | {} |",
                src_label,
                tgt_label,
                e.relation,
                e.score,
                e.reasons.join(", ")
            );
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_hyperedges(s: &mut String, graph: &GrapheniumGraph) {
    let _ = writeln!(s, "## Hyperedges");
    let _ = writeln!(s);
    if graph.hyperedges.is_empty() {
        let _ = writeln!(s, "_No hyperedges extracted._");
    } else {
        for h in &graph.hyperedges {
            let _ = writeln!(s, "**{}** (`{}`)", h.label, h.relation);
            let _ = writeln!(s, "- Nodes: {}", h.nodes.join(", "));
            let _ = writeln!(
                s,
                "- Confidence: {} ({:.2})",
                h.confidence, h.confidence_score
            );
            let _ = writeln!(s, "- Source: `{}`", h.source_file);
            let _ = writeln!(s);
        }
    }
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_communities(s: &mut String, stats: &[CommunityStats]) {
    let _ = writeln!(s, "## Communities");
    let _ = writeln!(s);
    if stats.is_empty() {
        let _ = writeln!(s, "_No communities detected._");
    } else {
        let _ = writeln!(s, "| ID | Focus | Size | Internal Edges | Cohesion |");
        let _ = writeln!(s, "|----|-------|------|----------------|----------|");
        for c in stats {
            let focus = c.focus.as_deref().unwrap_or("—");
            let _ = writeln!(
                s,
                "| {} | `{}` | {} | {} | {:.3} |",
                c.community_id, focus, c.size, c.internal_edges, c.cohesion
            );
        }
        let _ = writeln!(s);
        // Member lists for each community
        for c in stats {
            let _ = writeln!(
                s,
                "**Community {}** ({} nodes, cohesion {:.2}):",
                c.community_id, c.size, c.cohesion
            );
            // Show up to 20 members inline
            let shown: Vec<&str> = c.members.iter().map(|m| m.as_str()).take(20).collect();
            let suffix = if c.members.len() > 20 {
                format!(" … +{} more", c.members.len() - 20)
            } else {
                String::new()
            };
            let _ = writeln!(s, "> {}{}", shown.join(", "), suffix);
            let _ = writeln!(s);
        }
    }
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_ambiguous_edges(s: &mut String, graph: &GrapheniumGraph) {
    let _ = writeln!(s, "## Ambiguous Edges");
    let _ = writeln!(s);
    let ambiguous: Vec<_> = graph
        .edges_with_endpoints()
        .filter(|(_, _, e)| e.confidence == Confidence::Ambiguous)
        .collect();

    if ambiguous.is_empty() {
        let _ = writeln!(s, "_No AMBIGUOUS edges._");
    } else {
        let _ = writeln!(s, "| Source | Target | Relation | File |");
        let _ = writeln!(s, "|--------|--------|----------|------|");
        for (src, tgt, e) in ambiguous.iter().take(20) {
            let src_lbl = graph.node_data(src).map_or(*src, |n| n.display_label());
            let tgt_lbl = graph.node_data(tgt).map_or(*tgt, |n| n.display_label());
            let _ = writeln!(
                s,
                "| `{}` | `{}` | {} | `{}` |",
                src_lbl, tgt_lbl, e.relation, e.source_file
            );
        }
        if ambiguous.len() > 20 {
            let _ = writeln!(s, "\n_… and {} more._", ambiguous.len() - 20);
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_knowledge_gaps(s: &mut String, graph: &GrapheniumGraph) {
    let _ = writeln!(s, "## Knowledge Gaps");
    let _ = writeln!(s);
    let isolated: Vec<_> = graph.nodes().filter(|n| graph.degree(&n.id) == 0).collect();

    if isolated.is_empty() {
        let _ = writeln!(s, "_No isolated nodes._");
    } else {
        let _ = writeln!(
            s,
            "{} isolated node(s) with no connections:\n",
            isolated.len()
        );
        for n in isolated.iter().take(20) {
            let _ = writeln!(s, "- `{}` (`{}`)", n.display_label(), n.source_file);
        }
        if isolated.len() > 20 {
            let _ = writeln!(s, "\n_… and {} more._", isolated.len() - 20);
        }
    }
    let _ = writeln!(s);
    let _ = writeln!(s, "---");
    let _ = writeln!(s);
}

fn write_questions(s: &mut String, r: &ReportInput<'_>) {
    let _ = writeln!(s, "## Suggested Questions");
    let _ = writeln!(s);
    if r.analysis.questions.is_empty() {
        let _ = writeln!(s, "_No questions generated._");
    } else {
        for (i, q) in r.analysis.questions.iter().enumerate() {
            let _ = writeln!(s, "{}. {}", i + 1, q.question);
            let _ = writeln!(s, "   > _{}_", q.reason);
            let _ = writeln!(s);
        }
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyze::AnalysisResult;
    use crate::model::{Confidence, Edge, FileType, HyperEdge, Node};
    use tempfile::TempDir;

    fn make_input<'a>(
        graph: &'a GrapheniumGraph,
        stats: &'a [CommunityStats],
        analysis: &'a AnalysisResult,
    ) -> ReportInput<'a> {
        ReportInput {
            graph,
            community_stats: stats,
            analysis,
            corpus_warnings: &[],
            input_tokens: 1000,
            output_tokens: 500,
            title: "Test Graph".to_string(),
        }
    }

    fn empty_analysis() -> AnalysisResult {
        AnalysisResult {
            god_nodes: vec![],
            surprising: vec![],
            questions: vec![],
        }
    }

    #[test]
    fn report_contains_title() {
        let g = GrapheniumGraph::new();
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let md = render_report(&r);
        assert!(md.contains("Test Graph"));
    }

    #[test]
    fn report_contains_summary_table() {
        let mut g = GrapheniumGraph::new();
        g.upsert_node(Node::new("a", "A", FileType::Code, "a.rs"));
        g.upsert_node(Node::new("b", "B", FileType::Code, "b.rs"));
        g.add_edge(Edge::extracted("a", "b", "calls", "a.rs"));
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let md = render_report(&r);
        assert!(md.contains("| Nodes | 2 |"));
        assert!(md.contains("| Edges | 1 |"));
        assert!(md.contains("EXTRACTED"));
    }

    #[test]
    fn report_shows_ambiguous_edges() {
        let mut g = GrapheniumGraph::new();
        g.upsert_node(Node::new("a", "A", FileType::Code, "a.rs"));
        g.upsert_node(Node::new("b", "B", FileType::Code, "b.rs"));
        g.add_edge(Edge::new("a", "b", "uses", Confidence::Ambiguous, "a.rs"));
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let md = render_report(&r);
        assert!(md.contains("Ambiguous Edges"));
        assert!(md.contains("uses"));
    }

    #[test]
    fn report_shows_isolated_nodes() {
        let mut g = GrapheniumGraph::new();
        g.upsert_node(Node::new("lonely", "Lonely", FileType::Code, "x.rs"));
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let md = render_report(&r);
        assert!(md.contains("Knowledge Gaps"));
        assert!(md.contains("Lonely"));
    }

    #[test]
    fn report_shows_hyperedges() {
        let mut g = GrapheniumGraph::new();
        g.upsert_node(Node::new("a", "A", FileType::Code, "a.rs"));
        g.upsert_node(Node::new("b", "B", FileType::Code, "b.rs"));
        g.upsert_node(Node::new("c", "C", FileType::Code, "c.rs"));
        g.hyperedges.push(HyperEdge::new(
            "h1",
            "Auth flow",
            vec!["a".into(), "b".into(), "c".into()],
            "participate_in",
            Confidence::Inferred,
            "a.rs",
        ));
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let md = render_report(&r);
        assert!(md.contains("Auth flow"));
        assert!(md.contains("participate_in"));
    }

    #[test]
    fn write_report_creates_file() {
        let tmp = TempDir::new().unwrap();
        let g = GrapheniumGraph::new();
        let analysis = empty_analysis();
        let r = make_input(&g, &[], &analysis);
        let path = write_report(&r, tmp.path()).unwrap();
        assert!(path.exists());
        assert_eq!(path.file_name().unwrap(), "GRAPH_REPORT.md");
    }

    #[test]
    fn corpus_warnings_appear_in_report() {
        let g = GrapheniumGraph::new();
        let analysis = empty_analysis();
        let warnings = vec![CorpusWarning::TooSmall { word_count: 100 }];
        let r = ReportInput {
            graph: &g,
            community_stats: &[],
            analysis: &analysis,
            corpus_warnings: &warnings,
            input_tokens: 0,
            output_tokens: 0,
            title: "T".to_string(),
        };
        let md = render_report(&r);
        assert!(md.contains("Corpus Warnings"));
        assert!(md.contains("100"));
    }
}
